export const fatherlySayings: string[] = [
  "Crafting fatherly advice just for you.",
  "Formulating wisdom from a dad's heart.",
  "Pondering life lessons, fatherly style.",
  "Forging words of guidance from dad.",
  "Nurturing dreams with dad's insight.",
  "Weaving paternal advice, always present.",
  "Cultivating wisdom for your journey.",
  "Crafting the perfect sports metaphor.",
  "Crafting counsel, straight from dad.",
  "Molding your path with father's wisdom.",
  "Shaping your future, dad's guidance.",
  "Constructing fatherly advice, step by step.",
  "Assembling the puzzle of dad's counsel.",
  "Sculpting your success, with paternal guidance.",
];
